### ISSUE TITLE
v1.0.0 broke route flattening

### ISSUE THREAD

**Issue by pxDot** [dreamonkey/vue-routes-flattener#2]
The latest v1.0.0 update sadly broke the functionality of flattening the routes for me. Routes without components are not working at all now and throw the following error when trying to visit:
```
vue-router.esm-bundler.js?f6c4:3302 Error: Invalid route component
    at extractComponentsGuards (vue-router.esm-bundler.js?f6c4:1987:1)
    at eval (vue-router.esm-bundler.js?f6c4:3143:1)
```

**Comment by IlCallo** [comment]
Are you using Vue2? If yes, stick to 0.1 version, v1.0 only supports Vue3, as noted in its peer dependencies

**Comment by pxDot** [comment]
> Are you using Vue2? If yes, stick to 0.1 version, v1.0 only supports Vue3, as noted in its peer dependencies

I am using Vue 3 and vue-router v4

**Comment by IlCallo** [comment]
Interesting, can you create a repro for me to look at?

**Comment by pxDot** [comment]
I've found out some more information. Take e.g. a route like this:

```JS
...
{
  path: 'admin',
  redirect: '/admin/users', // <- remove this redirect and it works as expected
  children: [
    { path: 'users', component: () => import('pages/admin/Users.vue') },
    { path: 'user/:userId?', component: () => import('pages/admin/User.vue') },
  ],
},
...
```
It seems like the issue is from the redirect property. If I remove this line everything works as expected in v1.0.0 again.

**Comment by IlCallo** [comment]
I think it's working as intended, have you tried this?

```js
{
  path: 'admin',
  children: [
    { path: '', redirect: '/admin/users' },
    { path: 'users', component: () => import('pages/admin/Users.vue') },
    { path: 'user/:userId?', component: () => import('pages/admin/User.vue') },
  ],
},
```

**Comment by pxDot** [comment]
Yes it indeed works when writing a specific child route for the redirect. Not sure if this is intended behaviour though. I can live with declaring child routes for redirects like that but I thought flattening the routes would make it possible to use routes without components even with redirects (and every other property like e.g. `meta`). The top level redirects worked in the version before 1.0.0. Shouldn't it basically be part of the route flattening anyways?

I have another route with a top level redirect but that one has a top level component property, which is working fine even without a specific child route redirect. So the redirect is working with top level routes with components but not for top level routes without components.

**Comment by IlCallo** [comment]
Vue router accepts many different types of routes, among which there are the ones with component and the ones with redirect.
This package adds a new type of route, the "virtual" ones, which this package flat out before serving them to Vue Router.
This package understands what is a virtual route depending on the absence of component/s and redirect properties, and presence of children and path ones.

In the previous version we only checked for component property, because it was the fastest way to do it, now the check is stricter.

If you define a redirect into the root level, the package won't treat it like a virtual route and just pass it over, without doing the flattening.
Allowing to declare a redirect on the parent virtual route would cause confusion: wouldn't you expect that option to be copied to all its children, since it's doing a flattening? If we allow redirect, why not allowing component/s property too as a shortcut? And in that case, how would you understand what's a virtual route and what not?

The basic principle I followed is that virtual routes are, by definition, virtual: everything you define on them except path and children will be discarded, as they're just a placeholder for a path prefix

**Comment by pxDot** [comment]
> Allowing to declare a redirect on the parent virtual route would cause confusion: wouldn't you expect that option to be copied to all its children, since it's doing a flattening?

I wouldn't expect a redirect to be copied to the child routes the same as I wouldn't expect the component to be copied to the child routes as this is already the expected native behaviour in `vue-router` but I see the reasoning behind this now. I'm closing this, thank you.
